### ISSUE TITLE
Doctrine Entity for domain message

### ISSUE THREAD

**Issue by christian-kolb** [EventSaucePHP/DoctrineMessageRepository#5]
@frankdejonge When working with the doctrine message repository in a symfony project we run into issues that the domain message is not handled by doctrine as an entity. For example

- I don't get an info if the schema isn't up to date
- When running fixtures, the domain_messages table isn't truncated
- When using [automatic transaction rollback](https://github.com/dmaicher/doctrine-test-bundle) in test environments after every test, this does not work for the domain messages

Is there a reason why you don't use a Doctrine Entity here in this repository? 
If it's just because you haven't come around to do build it, I would implement it and add a pull request. I just don't want to do the work if there is some technical or architectural reason for it 🙂

**Comment by frankdejonge** [comment]
I wanted to keep the implementation to a minimum. An ORM is overkill for this process. Since it is in the critical path, you want to keep it light on abstractions if possible. Still, you can just see this repository as an example of what kind of interface you need, you can always just implement it using a Doctrine Entity to facilitate your needs. If it works for you, it's probably the right thing to do.

**Comment by christian-kolb** [comment]
Ok, yeah I thought there might be a good reason for it, that's why I wanted to ask first 🙂 
Thanks for the fast reply, then I will close this issue directly.

**Comment by frankdejonge** [comment]
👍 you're welcome!
